Pv horizontal tracking
martavp/atlite pull request #1
Opened 2023-02-21 09:00 UTC by Parisra

## Change proposed in this Pull Request

## Description
This pull request adds two options for solar tracking, namely 1-axis tracking on a North-South horizontal axis, and 1-axis tracking on a tilted North-South axis.

It also changes the name of 2-axes tracking from 'vh' to the more descriptive 'dual'.

## Motivation and Context
Since vertical tracking and dual tracking have already been added in a previous pull request(https://github.com/PyPSA/atlite/pull/255), horizontal is now added to complete the tracking options, especially since horizontal tracking is more common in reality today.

## How Has This Been Tested?
- The equations have been tested throughly and the results were compared to literature and data from PVGIS (https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html). A comparison between different tracking options is shown in the updated example notebook.
-  the functionality has also been tested .

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] I locally ran `pytest` inside the repository and no unexpected problems came up.
- [ ] I have adjusted the docstrings in the code appropriately.
- [ ] I have documented the effects of my code changes in the documentation `doc/`.
- [ ] I have added newly introduced dependencies to `environment.yaml` file.
- [x] I have added a note to release notes `doc/release_notes.rst`.
- [ ] I have used `pre-commit run --all` to lint/format/check my contribution

2023-03-06 01:00 UTC, martavp requested changes
Everything looks great @Parisa. Thanks for such a careful implementation which makes the revision easy.

Could you take care of implementing the small suggestions in my comments? 
Most significant are two suggestions for the renaming of variables. Let me know if you don't agree.

For the notebook, I suggest you delete the information on your local temp directory. Also, the final plot could be more useful if only a couple of summer days (instead of the full year) are plotted. 

As soon as you are done, I'll PR this to the main repository. Thanks, I'm glad we are finally able of implementing this

2023-03-13 10:01 UTC, Parisra commented on test/test_preparation_and_conversion.py
>      # calculate with tracking = 'vertical' and tracking = 'vh', and compare tracking option results
I think it's already done in a later commit.

2023-03-13 10:01 UTC, Parisra commented on atlite/pv/orientation.py
> +    elif tracking == "horizontal":  # horizontal tracking on north-south axis for horizontal panel
Good point, I agree that the explanation should be more straightforward.

2023-03-13 10:02 UTC, Parisra commented on atlite/pv/orientation.py
> +    elif tracking == "tilted_horizontal":  # horizontal tracking on north-south axis for tilted panel
I changed to 'horizontal tracking with tilted axis'.

2023-03-13 10:02 UTC, Parisra commented on atlite/pv/orientation.py
> +        surface_slope = abs(rotation)
Yes, It's done.

2023-03-13 10:02 UTC, Parisra commented on atlite/pv/orientation.py
> +            sun_azimuth - surface_azimuth))
I used it this way to match exactly the equations from the NREL study. Theoretically there should be no difference since cos(-x)=cos(x). I just thought it's better to use the exact same formula so it can be validated against the paper's equations easier.

2023-03-13 10:02 UTC, Parisra commented on atlite/pv/orientation.py
> +        surface_slope_initial= orientation["slope"]
Yes I totally agree it's not a very clear name. I added the comment as well

2023-03-13 10:02 UTC, Parisra commented on atlite/pv/orientation.py
> +
Yes, exactly, because I would need the 'R: rotation' to calculate the surface azimuth here with equation (2).

2023-03-13 10:02 UTC, Parisra commented on atlite/pv/orientation.py
> +        surface_azimuth_initial= orientation["azimuth"]
Yes I agree, It's done now.

2023-03-13 12:50 UTC, Parisra commented
There seems to be a problem merging this no matter what I do, so I will close this pull request and have done a new pull request using an updated branch (https://github.com/martavp/atlite/pull/2)

2023-03-13 12:50 UTC, closed without merging